[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["prompt-mannu.js"]  # Garante que o prompt seja incluído

[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
